# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8eccc9964dfab323022b67422de8119a8dcee8985baeff750c6c0547f8bb3bb42a66c5efb147e9143456336b8bec267a830f30b5aa6fcd8c27f6376f8acc6df

test:
  secret_key_base: 78e7b518e5c00afb4a59a688189395f6108224710d92ad0bfb90ff8f5d9d59a03675007643ce003adda567561f3fa4dae94d931ada0c1d4bb0cdf0cb9814f489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
